export const TESTRAY_CLIENT_ID = process.env.TESTRAY_CLIENT_ID
export const TESTRAY_CLIENT_SECRET = process.env.TESTRAY_CLIENT_SECRET
export const SLACK_BOT_TOKEN = process.env.SLACK_BOT_TOKEN
export const SLACK_CHANNEL_PAGE_MANAGEMENT =
	process.env.SLACK_CHANNEL_PAGE_MANAGEMENT
export const SLACK_CHANNEL_CMS = process.env.SLACK_CHANNEL_CMS
